DEF_CTR(1,0,1," EER_CC0: Coin mech 1 ")
DEF_CTR(1,2,2," EER_CC1: Coin mech 2 ")
DEF_CTR(1,4,3," EER_CC2: Coin mech 3 ")
DEF_CTR(1,6,4," EER_CC3: Coin mech 4 ")
DEF_CTR(1,8,5," EER_CCB: Bill acceptor ")
DEF_CTR(1,10,6," EER_CCX: Service credit switch ")
DEF_CTR(2,12,7," EER_0PTIME: idle time ")
DEF_CTR(2,15,8," EER_NEWCOINS: new games ")
DEF_CTR(2,18,9," EER_CONTCOINS: cont games ")
DEF_CTR(3,21,0," EER_ERRORS: count of EEPROM errors ")
DEF_OPT(7,25,0," EER_CNOPT: coin options ")
DEF_OPT(7,33,0," EER_CNVAL: Coin price options ")
DEF_OPT(7,41,0," EER_GMOPT: game options ")
DEF_OPT(7,49,0," EER_GUTS_OPT: GUTS options, incl. attract mute ")
DEF_CTR(1,57,0," EER_RESET: PROC non-powerup RESETS ")
DEF_CTR(1,59,0," EER_WR_RO: PROC write to read only mem ")
DEF_CTR(1,61,0," EER_RD_NEM: PROC read from non-existant mem ")
DEF_CTR(1,63,0," EER_WR_NEM: PROC write to non-existant mem ")
DEF_CTR(1,65,0," EER_ADRERR_R: PROC address alignment error on read ")
DEF_CTR(1,67,0," EER_ADRERR_W: PROC address alignment error on write ")
DEF_CTR(1,69,0," EER_BUSERR_I: PROC bus error on I fetch ")
DEF_CTR(1,71,0," EER_BUSERR_D: PROC bus error on D fetch ")
DEF_CTR(1,73,0," EER_SYSCALL: PROC SYSCALLS ")
DEF_CTR(1,75,0," EER_BREAKP: PROC Breakpoints ")
DEF_CTR(1,77,0," EER_ILGINS: PROC reserved instructions ")
DEF_CTR(1,79,0," EER_COPROC: PROC coprocessor unusables ")
DEF_CTR(1,81,0," EER_ARITH: PROC arithmetic overflows ")
DEF_CTR(1,83,0," EER_TRAP: PROC trap exceptions ")
DEF_CTR(1,85,0," EER_RESERV: PROC reserved exceptions ")
DEF_CTR(1,87,0," EER_FLOAT: PROC floating point exceptions ")
DEF_CTR(1,89,0," EER_UNDEF: PROC undefined exceptions ")
DEF_CTR(1,91,0," EER_OVERFL: PROC overflow checks ")
DEF_CTR(1,93,0," EER_DVDBY0: PROC divide by 0 ")
DEF_CTR(1,95,0," EER_RANGE: PROC range checks ")
DEF_CTR(1,97,0," EER_UHINT: PROC unhandled interrupt ")
DEF_CTR(1,99,0," EER_MOVERFL: PROC multiply overflow ")
DEF_CTR(1,101,0," EER_DATALST: SOFT sound data lost ")
DEF_CTR(1,103,0," EER_AUDRESET: SOFT sound proc resets ")
DEF_CTR(1,105,0," EER_LINKFAIL: SOFT LINK failures ")
DEF_CTR(1,107,0," EER_DSK_ERR: DISK any disk error ")
DEF_CTR(1,109,0," EER_DSK_AMNF: DISK address not found ")
DEF_CTR(1,111,0," EER_DSK_TK0NF: DISK trk 0 not found ")
DEF_CTR(1,113,0," EER_DSK_ABORT: DISK command abort ")
DEF_CTR(1,115,0," EER_DSK_IDNF: DISK ID not found ")
DEF_CTR(1,117,0," EER_DSK_UNCDTA: DISK uncorr data error ")
DEF_CTR(1,119,0," EER_DSK_TIMOUT: DISK device timeout ")
DEF_CTR(1,121,0," EER_DSK_WERR: DISK write fault ")
DEF_CTR(1,123,0," EER_DSK_CORR: DISK correctable data err ")
DEF_CTR(1,125,0," EER_FSYS_USEALT: FSYS Used alternate file ")
DEF_OPT(3,127,0," EER_AUD_VOL: audio volume level ")
DEF_OPT(1,131,0," EER_POT0L: Pot 0 - low limit ")
DEF_OPT(1,133,0," EER_POT1L: Pot 1 - low limit ")
DEF_OPT(1,135,0," EER_POT2L: Pot 2 - low limit ")
DEF_OPT(1,137,0," EER_POT3L: Pot 3 - low limit ")
DEF_OPT(1,139,0," EER_POT4L: Pot 4 - low limit ")
DEF_OPT(1,141,0," EER_POT5L: Pot 5 - low limit ")
DEF_OPT(1,143,0," EER_POT6L: Pot 6 - low limit ")
DEF_OPT(1,145,0," EER_POT7L: Pot 7 - low limit ")
DEF_OPT(1,147,0," EER_POT0H: Pot 0 - high limit ")
DEF_OPT(1,149,0," EER_POT1H: Pot 1 - high limit ")
DEF_OPT(1,151,0," EER_POT2H: Pot 2 - high limit ")
DEF_OPT(1,153,0," EER_POT3H: Pot 3 - high limit ")
DEF_OPT(1,155,0," EER_POT4H: Pot 4 - high limit ")
DEF_OPT(1,157,0," EER_POT5H: Pot 5 - high limit ")
DEF_OPT(1,159,0," EER_POT6H: Pot 6 - high limit ")
DEF_OPT(1,161,0," EER_POT7H: Pot 7 - high limit ")
